{"name": "Проверка ошибки логина курьера c невалидными значениями полей login, password", "status": "passed", "steps": [{"name": "Логинимся курьером", "status": "passed", "parameters": [{"name": "login", "value": "'nmYFzv'"}, {"name": "password", "value": "'xEjSwF'"}], "start": 1710019523196, "stop": 1710019523412}], "parameters": [{"name": "name", "value": "'nmYFzv'"}, {"name": "password", "value": "'xEjSwF'"}], "start": 1710019523196, "stop": 1710019523413, "uuid": "738b2579-ab30-4e40-86b2-edb702ce68c9", "historyId": "e65efc63d92ee69cb7bd39809a7c01bc", "testCaseId": "39c1d7417559ad0f95b1cbc5cf0d1629", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_invalid_credentials_return_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "WIN-VD1QDI3F4U5"}, {"name": "thread", "value": "4576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}