{"name": "Проверка ошибки логина курьера c невалидными значениями полей login, password", "status": "passed", "steps": [{"name": "Логинимся курьером", "status": "passed", "parameters": [{"name": "login", "value": "'dgrcwO'"}, {"name": "password", "value": "'ykozupraww'"}], "start": 1710019522929, "stop": 1710019523190}], "parameters": [{"name": "name", "value": "'dgrcwO'"}, {"name": "password", "value": "'ykozupraww'"}], "start": 1710019522929, "stop": 1710019523191, "uuid": "e03aac87-3e6f-4445-996c-5c506ab4ab8c", "historyId": "c3210355d6ee16ea7e984966fcb36288", "testCaseId": "39c1d7417559ad0f95b1cbc5cf0d1629", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_invalid_credentials_return_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "WIN-VD1QDI3F4U5"}, {"name": "thread", "value": "4576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}